# Generated by Django 5.1 on 2024-09-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_text',
            new_name='task_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
