# Generated by Django 5.1 on 2024-09-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0002_events_user_alter_events_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
