# Generated by Django 5.1 on 2024-09-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0003_alter_events_end_alter_events_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateField(),
        ),
    ]
