# Generated by Django 5.1 on 2024-09-08 15:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0004_alter_events_end_alter_events_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Entries',
        ),
    ]
