# Generated by Django 5.1 on 2024-09-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0005_rename_events_entries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='title',
            new_name='entry_name',
        ),
    ]
