# Generated by Django 5.1 on 2024-09-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0006_rename_title_entries_entry_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='entry_name',
            new_name='title',
        ),
    ]
